### ISSUE TITLE
Cannot display output file "index.html" on Ubuntu 22.04

### ISSUE THREAD

**Issue by StefanPofahl** [JuliaComputing/PlotlyLight.jl#29] opened 2023-06-08 15:18 UTC
see:
https://github.com/JuliaComputing/PlotlyLight.jl/issues/28

**Comment by StefanPofahl** [comment] 2023-06-08 19:35
The one in your readme works fine in this respect.

**Comment by StefanPofahl** [comment] 2023-06-17 08:10
I observe the same issue under `PlotlyJS.jl`, `savefig()` works fine, but the automatic display via default web-browser fails.
The temp html-file is there and the necessary access rights are given.

**Comment by joshday** [comment] 2023-06-17 12:02
If the issue isn't specific to PlotlyLight then I'm afraid there isn't anything to fix here, so I'm going to close the issue.  I would ask for help on the Julia slack or discourse.

**Closed by joshday** 2023-06-17 12:02 UTC
Labels: Needs reproducible example
